Update OC preview version
Lombiq/Audit-Trail-Extensions pull request #31
Opened 2024-05-28 12:08 UTC by sarahelsaig

2024-07-26 14:02 UTC, Piedone approved these changes

2024-07-28 20:03 UTC, Piedone requested changes

2024-07-28 20:03 UTC, Piedone commented on NuGet.config
Instead of keeping these up-to-date manually, please auto-add them to every project, [like we do with the Lombiq logo](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/Directory.Build.props#L16).

Related: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/504.

2024-07-28 20:29 UTC, sarahelsaig commented on NuGet.config
The NuGet.config is added to the solution (repo root), not the individual project like the Lombiq logo. So I don't think you can do that. Also, unlike the logo it is possible that we will have to customize these per-project. Also also, none of this is necessary when we don't use the OC preview package; or our own alphas after https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/504. So I think any automation should be done in that issue.

2024-07-28 20:36 UTC, Piedone commented on NuGet.config
OK, let's leave it.

2024-07-28 20:36 UTC, Piedone approved these changes

2024-07-28 23:02 UTC, merged